// Auto-generated by scripts/git-info.cjs
export const APP_VERSION: string = "1.0.0";
export const BRANCH_NAME: string = "main";
export const COMMIT_SHA: string = "424ff8a";
export const BUILD_TIME: string = "2026-09-07T11:45:21.709Z";

export const VERSION_INFO = {
  version: APP_VERSION,
  branch: BRANCH_NAME,
  commit: COMMIT_SHA,
  buildTime: BUILD_TIME,
};

export const getFormattedBuildTime = (): string => {
  if (!BUILD_TIME) return '';
  try {
    const d = new Date(BUILD_TIME);
    if (isNaN(d.getTime())) return BUILD_TIME;
    return d.toLocaleString('he-IL', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    });
  } catch {
    return BUILD_TIME;
  }
};

export const getFullVersionSummary = (): string => {
  const time = getFormattedBuildTime();
  const branchPart = BRANCH_NAME ? ` [${BRANCH_NAME}]` : '';
  const commitPart = COMMIT_SHA ? ` (commit: ${COMMIT_SHA})` : '';
  const timePart = time ? ` | נבנה: ${time}` : '';
  return `shelv.ai Scanner v${APP_VERSION}${branchPart}${commitPart}${timePart}`;
};

export default VERSION_INFO;
