const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function getGitInfo(repoRoot = path.resolve(__dirname, '..')) {
  // 1. Branch Name
  let branch =
    process.env.BRANCH_NAME ||
    process.env.VITE_BRANCH_NAME ||
    process.env.GITHUB_REF_NAME ||
    '';

  if (!branch || branch === 'HEAD') {
    try {
      branch = execSync('git rev-parse --abbrev-ref HEAD', {
        cwd: repoRoot,
        stdio: ['pipe', 'pipe', 'ignore'],
      })
        .toString()
        .trim();
    } catch {
      branch = '';
    }
  }

  if (!branch || branch === 'HEAD') {
    try {
      branch = execSync('git branch --show-current', {
        cwd: repoRoot,
        stdio: ['pipe', 'pipe', 'ignore'],
      })
        .toString()
        .trim();
    } catch {
      branch = '';
    }
  }

  if (!branch || branch === 'HEAD') {
    branch = 'main';
  }

  // 2. Commit SHA
  let commit =
    process.env.COMMIT_SHA ||
    process.env.VITE_COMMIT_SHA ||
    process.env.SHORT_SHA ||
    process.env.GITHUB_SHA ||
    '';

  if (!commit || commit === 'dev') {
    try {
      commit = execSync('git rev-parse --short HEAD', {
        cwd: repoRoot,
        stdio: ['pipe', 'pipe', 'ignore'],
      })
        .toString()
        .trim();
    } catch {
      commit = '';
    }
  }

  if (commit === 'dev') {
    commit = '';
  } else if (commit.length > 7) {
    commit = commit.slice(0, 7);
  }

  // 3. App Version
  let version =
    process.env.APP_VERSION ||
    process.env.VITE_APP_VERSION ||
    '';

  if (!version) {
    try {
      const gitTag = execSync('git describe --tags --always', {
        cwd: repoRoot,
        stdio: ['pipe', 'pipe', 'ignore'],
      })
        .toString()
        .trim();

      const semverMatch = gitTag.match(/^v?(\d+\.\d+\.\d+)/);
      if (semverMatch) {
        version = semverMatch[1];
      }
    } catch {
      // fallback
    }
  }

  if (!version) {
    try {
      const rootPkg = JSON.parse(
        fs.readFileSync(path.join(repoRoot, 'package.json'), 'utf8')
      );
      if (rootPkg.version) {
        version = rootPkg.version;
      }
    } catch {
      version = '1.0.0';
    }
  }

  const buildTime =
    process.env.BUILD_TIME ||
    process.env.VITE_BUILD_TIME ||
    new Date().toISOString();

  return {
    version,
    branch,
    commit,
    buildTime,
  };
}

function writeMobileVersionFile(repoRoot = path.resolve(__dirname, '..')) {
  const info = getGitInfo(repoRoot);
  const targetPath = path.join(repoRoot, 'mobile', 'src', 'version.ts');
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const content = `// Auto-generated by scripts/git-info.cjs
export const APP_VERSION: string = ${JSON.stringify(info.version)};
export const BRANCH_NAME: string = ${JSON.stringify(info.branch)};
export const COMMIT_SHA: string = ${JSON.stringify(info.commit)};
export const BUILD_TIME: string = ${JSON.stringify(info.buildTime)};

export const VERSION_INFO = {
  version: APP_VERSION,
  branch: BRANCH_NAME,
  commit: COMMIT_SHA,
  buildTime: BUILD_TIME,
};

export const getFormattedBuildTime = (): string => {
  if (!BUILD_TIME) return '';
  try {
    const d = new Date(BUILD_TIME);
    if (isNaN(d.getTime())) return BUILD_TIME;
    return d.toLocaleString('he-IL', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    });
  } catch {
    return BUILD_TIME;
  }
};

export const getFullVersionSummary = (): string => {
  const time = getFormattedBuildTime();
  const branchPart = BRANCH_NAME ? \` [\${BRANCH_NAME}]\` : '';
  const commitPart = COMMIT_SHA ? \` (commit: \${COMMIT_SHA})\` : '';
  const timePart = time ? \` | נבנה: \${time}\` : '';
  return \`shelv.ai Scanner v\${APP_VERSION}\${branchPart}\${commitPart}\${timePart}\`;
};

export default VERSION_INFO;
`;
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log('✓ Generated mobile/src/version.ts');
}

if (require.main === module) {
  const info = getGitInfo();
  const arg = process.argv[2];
  if (arg === '--write-mobile') {
    writeMobileVersionFile();
  } else if (arg && info[arg] !== undefined) {
    process.stdout.write(info[arg]);
  } else {
    console.log(JSON.stringify(info, null, 2));
  }
}

module.exports = { getGitInfo, writeMobileVersionFile };
